version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: moneywise-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  app:
    build: .
    container_name: moneywise-app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "${PORT}:3000"
    depends_on:
      - db
    env_file:
      - .env
    command: npm run dev

  adminer:
    image: adminer
    container_name: moneywise-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
